global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'my_app'
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        filters:
          - name: label
            values: ["com.mycompany.metrics=true"]
    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        target_label: container_name
      - source_labels: [__meta_docker_container_ip]
        target_label: container_ip
    metric_relabel_configs:
      - source_labels: [container_name]
        target_label: app
        regex: '.*_(app)_.*'
        replacement: '$1'
